### ISSUE TITLE
不参加のメンバーのスコアが0になっている

### ISSUE THREAD

**Issue by IshidaKazuki0605** [NowellGartelt/ScoreBoard#3]
たとえばハイフンや「不参加」などを書くべきではありませんか？

**Comment by NowellGartelt** [comment]
ゲームに参加した場合、スコアが0になることはないため、0=不参加という扱いです。
ただ、見た目が分かりづらいという問題はあるので、0の場合は「-」を表示するなど、対応を考えるべきかとは思っています。
